# Generated by Django 5.0.6 on 2024-07-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250)),
                ('satisfaction_range', models.IntegerField(max_length=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtaawetu_app.amenities')),
            ],
            options={
                'ordering': ['-comment'],
            },
        ),
    ]
