# Generated by Django 5.0.6 on 2024-07-13 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaawetu_app', '0003_amenities_amenity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfaction',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
