# Generated by Django 5.0.6 on 2024-07-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaawetu_app', '0005_alter_satisfaction_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satisfaction',
            old_name='name',
            new_name='amenity',
        ),
    ]
