# Generated by Django 5.0.6 on 2024-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaawetu_app', '0007_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='blob',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
