# Generated by Django 5.0.6 on 2024-07-23 06:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaawetu_app', '0008_research_blob_alter_research_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
